networks:
  mynetwork:
    driver: bridge

services:
  mysql:
    image: mysql
    container_name: mysql
    networks:
      - mynetwork
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=agenda_fit
      - MYSQL_ROOT_PASSWORD=123

  app:
    build: .
    container_name: agenda-fit
    networks:
      - mynetwork
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/agenda_fit
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=123
    ports:
      - "8080:8080"
